### Student Performance Analysis with Linear Algebra

In [1]:
import numpy as np

In [2]:
# The Matrices for each Student
student_1 = np.array([80, 70, 90])
student_2 = np.array([60, 85, 75])
student_3 = np.array([95, 88, 92])
student_4 = np.array([70, 60, 65])



Student_matrix = np.array([[80, 70, 90],
                           [60, 85, 75],
                           [95, 88, 92],
                           [70, 60, 65]])

print("Scores (4x3)=\n", Student_matrix)

Scores (4x3)=
 [[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


#### Total Scores per Student (Vector Addition)



student 1 = [80 + 70 + 90] = 240<br>
student 2 = [60 + 85 + 75] = 220<br>
student 3 = [95 + 88 + 92] = 275<br>
student 4 = [70 + 60 + 65] = 195

In [3]:
scores_per_student = np.sum(Student_matrix, axis=1)
print(scores_per_student)

i = 1
for student_score in scores_per_student:
    print(f"Total Scores for Student {i} = {student_score}")
    i+=1

[240 220 275 195]
Total Scores for Student 1 = 240
Total Scores for Student 2 = 220
Total Scores for Student 3 = 275
Total Scores for Student 4 = 195


#### Applying Weights (Scaler Multiplication)

In [4]:
Student_matrix[:, 0] = 2 *(Student_matrix[:, 0])
print("Subject Weight =\n", Student_matrix)


# print(Student_matrix)

Subject Weight =
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


### Average score by each subject

In [5]:
average_score_per_subject = np.average(Student_matrix, axis = 0)
print(average_score_per_subject)
i = ["Maths", "English", "Science"]

for wale, average_score in zip(i, average_score_per_subject):
    print(f"Average score for {wale} = {average_score}")



[152.5   75.75  80.5 ]
Average score for Maths = 152.5
Average score for English = 75.75
Average score for Science = 80.5


### Final Grades using Matrix Multiplication


In [6]:
weight_vector = np.array([0.5, 0.3, 0.2])

maths_final_grade = np.dot(weight_vector[0], Student_matrix[:,0])
print("Mathematics Final Grade:\n", maths_final_grade.reshape(4,1))


english_final_grade = np.dot(weight_vector[1], Student_matrix[:,1])
print("English Final Grade:\n", english_final_grade.reshape(4,1))


science_final_grade = np.dot(weight_vector[2], Student_matrix[:,2])
print("Science Final Grade:\n", science_final_grade.reshape(4,1))

Mathematics Final Grade:
 [[80.]
 [60.]
 [95.]
 [70.]]
English Final Grade:
 [[21. ]
 [25.5]
 [26.4]
 [18. ]]
Science Final Grade:
 [[18. ]
 [15. ]
 [18.4]
 [13. ]]


### Comparing Students(Vector Subtraction)

In [7]:
comppare_student = np.diff(scores_per_student)
print(comppare_student)

performance1 = scores_per_student[2] - scores_per_student[1]
performance2 = scores_per_student[2] -scores_per_student[0]
performance3 = scores_per_student[2] - scores_per_student[3]

print("Overall, student 3 is the most brilliant with the highest grade difference",performance1, performance2, 'and', performance3)
 

[-20  55 -80]
Overall, student 3 is the most brilliant with the highest grade difference 55 35 and 80


### ADD-ON EXERCISES


##### QUESTION ONE
$$
Scores = \begin{bmatrix}
80 & 70 & 90 & 50 \\
60 & 85 & 75 & 60 \\
95 & 88 & 92 & 70 \\
70 & 60 & 65 & 80 \\
70 & 55 & 75 & 60
\end{bmatrix}


In [8]:
scores = np.array([[80,70,90,50],[60,85,75,60],[95,88,92,70],[70,60,65,80],[70,55,75,60]])


student1_scores = np.array([80,70,90,50])
student2_scores = np.array([60,85,75,60])
student3_scores = np.array([95,88,92,70])
student4_scores = np.array([70,60,65,80])
student5_scores = np.array([70,55,75,60])
print(scores)

[[80 70 90 50]
 [60 85 75 60]
 [95 88 92 70]
 [70 60 65 80]
 [70 55 75 60]]


#### Total Score and Average per subject

In [9]:
total_score = np.sum(scores, axis = 1)
print ("Student total scores", total_score)

i = 1
for stu_total_scores in total_score:
    print(f"Total score for Student {i} = {stu_total_scores}")
    i += 1

avg_score = np.average(scores, axis = 0)
print("Average per subject =", avg_score)
j = ["Math", "English", "Science", "AI"]
     
for average, avg_per_subject in zip(j,avg_score):
     print(f"Average Score in {average} = {avg_per_subject}")

Student total scores [290 280 345 275 260]
Total score for Student 1 = 290
Total score for Student 2 = 280
Total score for Student 3 = 345
Total score for Student 4 = 275
Total score for Student 5 = 260
Average per subject = [75.  71.6 79.4 64. ]
Average Score in Math = 75.0
Average Score in English = 71.6
Average Score in Science = 79.4
Average Score in AI = 64.0


#### QUESTION TWO

In [10]:
science_scaler = 3 *(scores[:, 2])
print("Scaler Weight for Science=\n", science_scaler)

scores[:, 2] = 3 *(scores[:, 2])
print("Scores Total =\n", scores)

Scaler Weight for Science=
 [270 225 276 195 225]
Scores Total =
 [[ 80  70 270  50]
 [ 60  85 225  60]
 [ 95  88 276  70]
 [ 70  60 195  80]
 [ 70  55 225  60]]


###  QUESTION THREE

In [11]:
new_weight = np.array([0.4, 0.2, 0.3, 0.1])

grade_for_math = np.dot(new_weight[0], scores[:,0])
print("Final Grade for Mathematics:\n", grade_for_math.reshape(5,1))


grade_for_eng = np.dot(new_weight[1], scores[:,1])
print("Final Grade for English:\n", grade_for_eng.reshape(5,1))


grade_for_science = np.dot(new_weight[2], scores[:,2])
print("Final Grade for Science:\n", grade_for_science.reshape(5,1))


grade_for_ai = np.dot(new_weight[3], scores[:,3])
print("Final Grade for AI:\n", grade_for_ai.reshape(5,1))

Final Grade for Mathematics:
 [[32.]
 [24.]
 [38.]
 [28.]
 [28.]]
Final Grade for English:
 [[14. ]
 [17. ]
 [17.6]
 [12. ]
 [11. ]]
Final Grade for Science:
 [[81. ]
 [67.5]
 [82.8]
 [58.5]
 [67.5]]
Final Grade for AI:
 [[5.]
 [6.]
 [7.]
 [8.]
 [6.]]
